org_uri: "https://api.enterprise.apigee.com/v1/organizations/{{ APIGEE_ORGANIZATION }}"
products_uri: "{{ org_uri }}/apiproducts"
apps_uri: "{{ org_uri }}/apps"
developers_uri: "{{ org_uri }}/developers"
retain_hours:  "{{ (lookup('env', 'retain_hours') or 72) }}"
product_filter: "{{ lookup('env', 'PRODUCT_FILTER') }}"
portals_base_uri: "https://apigee.com/portals/api/sites"

#      https://apigee.com/portals/api/sites/nhsd-nonprod-developerportal/audiencesenabled
#
#  nhsd-nonprod/portals/nhsd-nonprod-developerportal/accounts/teams
#https://apigee.com/consumers/api/providers/4ac22135-49bf-4e7e-b79b-93ad2ceb3aa3/teams
#
#  https://apigee.com/organizations/nhsd-nonprod/portals/nhsd-nonprod-developerportal/accounts/teams
#  https://apigee.com/portals/api/sites/nhsd-nonprod-developerportal/accounts/teams
#                    "{{ portals_base_uri }}/{{ portal_id }}/apidocs"