- name: deploy ecs proxies
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    account:  "{{ lookup('env','account') }}"
    service_id: "{{ lookup('env','service_id') }}"
    APIGEE_ENVIRONMENT: "{{ lookup('env','APIGEE_ENVIRONMENT') }}"
    SANDBOX: "{{ lookup('env','SANDBOX') }}"
    pr_number: "{{ lookup('env','pr_number') }}"
    APIGEE_HOSTNAME: "{{ '' if APIGEE_ENVIRONMENT == 'prod' else APIGEE_ENVIRONMENT + '.' }}api.service.nhs.uk"
    apigee_uri: "https://{{ APIGEE_HOSTNAME }}"
    aws_profile: "deploy-{{ APIGEE_ENVIRONMENT | lower }}-{{ service_id }}"


  pre_tasks:

    - name: check account
      fail:
        msg: "account not set"
      when: not account

    - name: check service_id
      fail:
        msg: "service_id not set"
      when: not service_id

    - name: check APIGEE_ENVIRONMENT
      fail:
        msg: "APIGEE_ENVIRONMENT not set"
      when: not APIGEE_ENVIRONMENT

    - name: check SANDBOX
      fail:
        msg: "SANDBOX not set"
      when: not SANDBOX

    - name: include vars
      include_vars:
        file: "{{ lookup('env', 'PROXY_VARS_FILE') | expandvars | expanduser | realpath }}"

  roles:
    - setup-facts
    - deploy-ecs-proxies