- name: remove old ecs pr deployments
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  vars:
    account:  "ptl"
    APIGEE_ENVIRONMENT: "internal-dev"
    aws_profile: "apm_{{ account }}"

  roles:
    - setup-facts
    - remove-old-ecs-pr-deploys
