name: Test deployments

on: [pull_request]

jobs:
  test_deployments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts
      uses: actions/checkout@v2

    - name: Test Pull Request Deployments
      env:
        AZURE_TOKEN: "${{ secrets.AZURE_TOKEN }}"
      run: |
        export BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
        export NOTIFY_COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
        export UTILS_PR_NUMBER="${{ github.event.pull_request.number }}"
        echo UTILS_PR_NUMBER=${UTILS_PR_NUMBER}
        echo BRANCH_NAME=${BRANCH_NAME}
        echo NOTIFY_COMMIT_SHA=${NOTIFY_COMMIT_SHA}
        python3 scripts/test_pull_request_deployments.py
